Update matplotlib minimum pin
Pin needs to be bumped due to use of 3D features that appear to have been released in mpl 3.10.0 (https://github.com/matplotlib/matplotlib/commit/29d886eab5d5ea54b023bb2601a0f83055ae4104).

Should fix `ImportError: cannot import name '_viewlim_mask' from 'mpl_toolkits.mplot3d.art3d'`.